/**
 * Locale-aware navigation helpers generated by next-intl.
 * Import Link, useRouter, usePathname, redirect from here
 * instead of from 'next/link' or 'next/navigation' to get
 * automatic locale prefix handling.
 */
import { createNavigation } from 'next-intl/navigation';

export const locales = ['fr', 'en', 'ar'] as const;
export type Locale = (typeof locales)[number];

export const { Link, redirect, usePathname, useRouter, getPathname } =
  createNavigation({
    locales,
    localePrefix: 'always',
  });
