api:
  dashboard: false

log:
  level: INFO

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock" 
    exposedByDefault: false
    network: traefik_public

certificatesResolvers:
  letsencrypt:
    acme:
      email: contact@itinup.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
